### ISSUE TITLE
Unit circle not shown in chapter WebGPU Rotation

### ISSUE THREAD

**Issue by UnluckyNinja** [webgpu/webgpufundamentals#123]
Page that has the issue: https://webgpufundamentals.org/webgpu/lessons/webgpu-rotation.html
Cause seems at:  https://github.com/webgpu/webgpufundamentals/blob/7feee887925742a91752bd0ec137729da2c3c6d9/webgpu/resources/js/unit-circle.js#L31
I think it could be fixed by prepending another "../"

**Comment by greggman** [comment]
thanks, fixed.
