### ISSUE TITLE
confusion with data types

### ISSUE THREAD

**Issue by KTibow** [webgpu/webgpufundamentals#126]
https://webgpufundamentals.org/webgpu/lessons/webgpu-fundamentals.html#a-run-computations-on-the-gpu

the code snippets use `vec3u` (doesn't work)
the code demo uses `vec3<u32>` (works)

which one's proper?

**Comment by greggman** [comment]
`vec3u` works

https://jsgist.org/?src=990b3091ae56a65364d70162b9189a1d

maybe you had a typo? Or are using a really old browser?

**Comment by KTibow** [comment]
that's odd, i swear i copied the code verbatim and it gave me empty values with `vec3u` (maybe it was an issue with my hot reload?)

anyway, i tried again and am no longer having this problem, so i will close the issue.
