### ISSUE TITLE
Possible sign issues in 3D rotation matrices of Ortographic Projection article

### ISSUE THREAD

**Issue by Tomycj** [webgpu/webgpufundamentals#139]
If positive rotation is counter-clockwise and we're on a right-handed coordinate system, then:

+Z rotated +90° around +X gives -Y, but the equation representing the X rotation 3D matrix _(newY = y *  c + z * s)_ gives +Y as a result.

+Z rotated +90° around +Y gives +X, and the equation representing the Y rotation 3D matrix _(newX = x *  c + z * s)_ gives the correct result, but it does not match the ilustrated matrix (the last sine has the opposite sign).

+X rotated +90° around +Z gives +Y, but the equation representing the Z rotation 3D matrix _(newY = x * -s + y * c)_ gives -Y as a result, and it does not match the ilustrated matrix (which does give the correct result). The ilustrated matrix does not match the code implementation shown below it.

It's possible that I'm interpreting something incorrectly. Rotation of the F in the interactive examples seems to work correctly, positive when counter-clockwise on a right-handed coordinate system.

**Comment by greggman** [comment]
The samples flip y

```
        // flip Y
        let clipSpace = flippedClipSpace * vec2f(1, -1);
```

which makes positive Y down (same as Canvas 2D)

This is [covered in the previous article](https://webgpufundamentals.org/webgpu/lessons/webgpu-translation.html). 

Does that answer your question?

**Comment by Tomycj** [comment]
More than a question it was just a heads-up, because it looks like the equations don't match the matrices in some cases. This is independent on the direction of the Y axis, as long as it remains a right-handed coordinate system:

This is the ilustration of the 2D rotation matrix:
![image](https://github.com/user-attachments/assets/3a968dc7-880c-4b2c-bc2e-a5be596202d1)
And in the [matrix math](https://webgpufundamentals.org/webgpu/lessons/webgpu-matrix-math.html) article its corresponding equation is:
![image](https://github.com/user-attachments/assets/40cae45f-97fa-4ef2-ac26-64b25bf2db44)

But then in the [ortographic projection](https://webgpufundamentals.org/webgpu/lessons/webgpu-orthographic-projection.html) article we have:
![image](https://github.com/user-attachments/assets/e8d2f656-cede-4c5f-98d3-940d859d81c7)

for the same matrix. This was for the Z rotation matrix, but the Y rotation matrix seems to have a sign discrepancy too, between its equation and its ilustration.

Separately, the X rotation matrix may be rotating in the opposite direction:

**Comment by greggman** [comment]
Thanks for pointing out those issues. I'll take a look.

**Comment by greggman** [comment]
Do you want to double check the fix?

https://github.com/webgpu/webgpufundamentals/pull/140/files

**Comment by Tomycj** [comment]
The equations look good! #148 changes the ilustrations to match them.

The actual code does not use these corrected matrices, some signs remain flipped. Maybe the interactive examples are rotating the F correctly because the incorrect signs make the matrices rotate in the opposite direction, which is what we want: instead of rotating the camera, we're rotating the world in the opposite direction.

In any case I don't change that code because it seems it's used in a lot of places.

**Comment by greggman** [comment]
AFIACT the actualy running code is correct 

Here's three.js's code, glMatirx is the same as well

three x rotation

```
1,  0,  0,  0
0,  c,  s,  0
0, -s,  c,  0
0,  0,  0,  1
```

code in article x rotation and examples

```
    dst[ 0] = 1;  dst[ 1] = 0;   dst[ 2] = 0;  dst[ 3] = 0;
    dst[ 4] = 0;  dst[ 5] = c;   dst[ 6] = s;  dst[ 7] = 0;
    dst[ 8] = 0;  dst[ 9] = -s;  dst[10] = c;  dst[11] = 0;
    dst[12] = 0;  dst[13] = 0;   dst[14] = 0;  dst[15] = 1;
```

And glMatrix: https://glmatrix.net/docs/mat4.js.html#line988

three y rotation

```
c,  0, -s,  0,
0,  1,  0,  0,
s,  c,  0,  0,
0,  0,  0,  1,
```

code in article 

```
    dst[ 0] = c;  dst[ 1] = 0;  dst[ 2] = -s;  dst[ 3] = 0;
    dst[ 4] = 0;  dst[ 5] = 1;  dst[ 6] = 0;   dst[ 7] = 0;
    dst[ 8] = s;  dst[ 9] = 0;  dst[10] = c;   dst[11] = 0;
    dst[12] = 0;  dst[13] = 0;  dst[14] = 0;   dst[15] = 1;
```

and glMatrix: https://glmatrix.net/docs/mat4.js.html#line1023

three z rotation

```
 c,  s,  0,  0,
-s,  c,  0,  0,
 0,  0,  1,  0,
 0,  0,  0,  1,
```

code in article z rotation

```
    dst[ 0] = c;   dst[ 1] = s;  dst[ 2] = 0;  dst[ 3] = 0;
    dst[ 4] = -s;  dst[ 5] = c;  dst[ 6] = 0;  dst[ 7] = 0;
    dst[ 8] = 0;   dst[ 9] = 0;  dst[10] = 1;  dst[11] = 0;
    dst[12] = 0;   dst[13] = 0;  dst[14] = 0;  dst[15] = 1;
```

And glMatrix: https://glmatrix.net/docs/mat4.js.html#line1058

I think if I fixed the article,

**Comment by Tomycj** [comment]
Ok so #150 changes the matrix ilustrations to match the equations, they also match glMatrix code. Now I see that the code indeed is already correct.

To clarify what is confusing at least to me, and I may be mistaken: It's that layout for the code and the diagram of the Three matrices. Because laid out in a 4x4 grid one would expect they showed the matrix they represent, but they don't: they're transposed and don't visually match the matrix ilustrations. For example I would display the Three X rotation matrix (that rotates counter clockwise along the X axis) like this instead:

    1  0  0  0
    0  c -s  0
    0  s  c  0
    0  0  0  1

Where rotating +Y by 90° gives +Z:

    1  0  0  0     0     0
    0  0 -1  0  X  1  =  0
    0  1  0  0     0     1
    0  0  0  1     1     1

In any case, it seems this issue has been solved! I asume at this point I'm supposed to close the issue so I'll go ahead and do it. Thank you very much!

**Comment by greggman** [comment]
Thank you for helping fix this.

Yes, it's confusing. The GL spec says for a given matrix

```
   0  1  2  3
   4  5  6  7
   8  9 10 11
  12 13 14 15
```

These rows (in C, C++, JavaScript, etc) are columns of the matrix

```
   0  1  2  3   <- column 0
   4  5  6  7   <- column 1
   8  9 10 11   <- column 2
  12 13 14 15   <- column 3
```

This is mentioned in [the article on matrix math](https://webgpufundamentals.org/webgpu/lessons/webgpu-matrix-math.html#a-columns-are-rows)

It's been confusing people for 30+ years 😅
