### ISSUE TITLE
Minor but confusing typos in an example on the WGSL page

### ISSUE THREAD

**Issue by tomholcomb** [webgpu/webgpufundamentals#179]
The example code under the `vector construction` heading on the [WGSL](https://webgpufundamentals.org/webgpu/lessons/webgpu-wgsl.html) page has three minor typos that I'd like to fix:

The sample says:
```wgsl
let a = vec4f(1, 2, 3, 4);
let b = vec2f(2, 3);
let c = vec4f(1, b, 4);
let d = vec2f(1, a.yz, 4);
let e = vec2f(a.xyz, 4);
let f = vec2f(1, a.yzw);
```

and I believe it should say:

```wgsl
let a = vec4f(1, 2, 3, 4);
let b = vec2f(2, 3);
let c = vec4f(1, b, 4);
let d = vec4f(1, a.yz, 4);
let e = vec4f(a.xyz, 4);
let f = vec4f(1, a.yzw);
```
In others words, `d`, `e`, and `f` are `vec4f`s, not `vec2f`s.

**Comment by greggman** [comment]
fixed via: https://github.com/webgpu/webgpufundamentals/pull/180
