### ISSUE TITLE
Tutorial of WebGPU Multisampling

### ISSUE THREAD

**Issue by sucong0826** [webgpu/webgpufundamentals#72]
@greggman Could you please continue writing the tutorial about WebGPU multisampling? https://webgpufundamentals.org/webgpu/lessons/webgpu-multisampling.html I am working on the related feature. It must be helpful to the developers who want to use MSAA.

**Comment by sucong0826** [comment]
@greggman appreciate! I will read the article carefully that you suggest. : )

**Comment by greggman** [comment]
added : https://webgpufundamentals.org/webgpu/lessons/webgpu-multisampling.html
