### ISSUE TITLE
How to better render to multiple canvases?

### ISSUE THREAD

**Issue by sucong0826** [webgpu/webgpufundamentals#73]
https://webgpufundamentals.org/webgpu/lessons/webgpu-from-webgl.html

> But, because of that, unlike WebGL, you can use one WebGPU device to render to multiple canvases. 🎉🤩

Hi @greggman , while I was reading the article WebGPU from WebGL, this part attracted my attention. I tried to adopt a similar idea to reuse the same GPUDevice to render to multiple canvases but failed finally. I create a proxy class named WebGPURenderer which is used to finish rendering that `requestAnimationFrame()` triggers it to be called. I wish WebGPURenderer could reuse the same GPUDevice and serve for multiple canvases. However, every time it serves for another canvas, I need to configure GPUCanvasContext again for the next canvas.
For example, here are two canvases on the screen and this round of rendering is coming, I need to configure the GPUCanvasContext for the first canvas and then configure it one more time for the second canvas. I found this kind of mechanism costs a lot.
From my understanding of your words, I think you want to say that the `device` attribute can be set with the same GPUDevice when each GPUCanvasContext calls `configure()`.  **So my question is, how can I better render to multiple canvases?** 

``` javascript
this.#mWGPUContext.configure({
        device: this.#mDevice,
        format: this.#mFormat,
        alphaMode: 'premultiplied',
});
```

**Comment by greggman** [comment]
The reason to use 1 device is so you can share resources. A Texture, Buffer, Pipeline, ShaderModule, etc can only be used with a single device. If you have 2 or more devices, then each texture, buffer, pipeline, shaderModule has to be created separately for each device.

It is a good idea to call `unconfigure` when you're done with a canvas and have removed it from the DOM. That will let the canvas free its textures. Of course the browser will eventually free unused canvases and their resources by itself but calling `unconfigure` makes that explicit.

**Comment by sucong0826** [comment]
> The reason to use 1 device is so you can share resources. A Texture, Buffer, Pipeline, ShaderModule, etc can only be used with a single device. If you have 2 or more devices, then each texture, buffer, pipeline, shaderModule has to be created separately for each device.

For example, Will I get two separated GPUDevice objects if I call `adapter.requestDevice()` twice? I am curious about this result. If calling `adapter.requestDevice()` multiple times in the same thread will get multiple different GPUDevice objects, it is meaningful to reuse the same GPUDevice. But how GPU side return the GPUDevice to the client side?

**Comment by greggman** [comment]
It put up a multiple canvas article: https://webgpufundamentals.org/webgpu/lessons/webgpu-multiple-canvases.html
