### ISSUE TITLE
Cross product ilustrations in Camera article shows the resulting vector pointing in the opposite way

### ISSUE THREAD

**Issue by Tomycj** [webgpu/webgpufundamentals#83]
In the article about cameras there's an ilustration showing how to get the X axis from the Z axis, by doing UP cross Z, but the resulting vector points in the wrong (opposite) direction. UP cross Z should point to the right (looking from the back of the camera). 

The ilustration for the Y axis has the same issue, but the final Y axis direction is correct because the two issues "cancel out".
![image](https://github.com/webgpu/webgpufundamentals/assets/51275588/1984bd83-cbad-4312-8562-9ff6cfcefe3f)

**Comment by greggman** [comment]
Thanks for pointing that out
