### ISSUE TITLE
Issue with navigation in translated articles

### ISSUE THREAD

**Issue by ErdtR** [webgpu/webgpufundamentals#97]
**Issue**: Navigation from one trasnlated article to another already translated article doesn't work.

**How to reproduce**: 

Let's use this Inter-stage Variables article as example. For english version of the artciale we got this href value for a _previous article_ which is exactly what we expecting here:

<img width="1198" alt="image" src="https://github.com/webgpu/webgpufundamentals/assets/12209405/332553fb-2799-425c-99bc-c0860966a8a6">

Now let's change the language to Ukrainian (Українська). We will get this result:

<img width="1195" alt="image" src="https://github.com/webgpu/webgpufundamentals/assets/12209405/adb8cbaf-db72-45bb-8f0c-ad8019bf0ff3">

The `../webgpu-fundamentals.html` will navigate us to the English version of Fundamentals article. I expect it to be `webgpu-fundamentals.html` so we can go to already translated version.

@greggman I am not sure if that actually a bug or something I am doing wrong. I was trying to figure it out but lost myself in the gruntfile. In any case I'll be happy to help with this issue.

**Comment by greggman** [comment]
It looks like a bug. I'll look into it asap.

**Comment by greggman** [comment]
I pushed a fix. It should update soon.

**Comment by ErdtR** [comment]
Thanks, now it works as expected. I think we can close the issue.
